name: WorkFlow for Building logging-dev image

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
    paths:
      - 'go.mod'
      - 'go.sum'
      - 'main.go'
      - 'Dockerfile'
      - 'VERSION'

env:
  REPO_EW: 'birdhk'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    name: Build logging-dev Image
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.x

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push image
        run: |
          tag=$(cat VERSION | tr -d " \t\n\r")
          make build -e EW_IMG=${{ env.REPO_EW }}/logging-dev:$tag